package com.gradle;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.gradle.util.Library;

import java.util.Enumeration;
import java.util.Properties;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        Properties p = System.getProperties();
        Enumeration keys = p.keys();
        while (keys.hasMoreElements()) {
            String key = (String)keys.nextElement();
            String value = (String)p.get(key);
            System.out.println(key + ": " + value);
        }
        //System.out.println("Hello" + System.getProperty("app.greeting"));
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
